build_from:
  amd64: ghcr.io/home-assistant/amd64-addon-base-python:3.12-alpine3.19
  aarch64: ghcr.io/home-assistant/aarch64-addon-base-python:3.12-alpine3.19
  armv7: ghcr.io/home-assistant/armv7-addon-base-python:3.12-alpine3.19
